# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory:
                users:
                    ryan:
                        password: $2y$12$fnobTzPnjc1RwAJ6P.MirOUdoNN6Vvxo/0kZOGFRvl0ZH4ccW9av2
                        roles: 'ROLE_USER'
                    admin:
                        password: $2y$12$9gA0F0XKbth4lfDWeDJB6ufhnOr4uiNUli9T2Ny5Nv9n9M.76fhW2
                        roles: 'ROLE_ADMIN'

        our_db_provider:
            entity:
                class: AppBundle:Person
                property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            provider: our_db_provider
            anonymous: ~

            form_login:
                login_path: login
                check_path: login

            logout:
                path:   /logout
                target: /

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/instructor, roles: ROLE_INSTRUCTOR }
        - { path: ^/member, roles: ROLE_MEMBER }

    encoders:
        AppBundle\Entity\Person:
            algorithm: bcrypt

        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12

